import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Provider } from '@/providers';
import { cn } from '@/shared/utils';
import Link from 'next/link';
import Image from 'next/image';


import BrandLogoAsset from '@/public/brand/logo.png';


// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'shield.sec',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(inter.className, 'antialiased')}
      >
        <header className="w-full px-8 py-4">
          <Link href='#' shallow>
            <Image {...BrandLogoAsset} alt="shield.sec" />
          </Link>
        </header>
        
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
